version: '3'
services:
  langchain-streamlit-agent:
    image: langchain-streamlit-agent:latest
    build: ./app
    command: streamlit run streamlit_agent/chat_pandas_df.py --server.port 8051
    volumes:
      - ./streamlit_agent/:/app/streamlit_agent
    ports:
      - 8051:8051
      # .github/workflows/auto-evolve.yml
name: Strategy Evolution Pipeline

on:
  schedule:
    - cron: '0 18 * * 1-5'  # Market close on weekdays

jobs:
  evolve:
    runs-on: quantum-safe-runner
    steps:
      - name: Check performance
        run: python -m frontier_trader.monitor
      
      - name: Generate new version
        if: ${{ needs.monitor.outputs.upgrade == 'true' }}
        run: python -m evolution.generator
        
      - name: Deploy to production
        if: ${{ needs.test.outputs.passed == 'true' }}
        run: git push production-strategies main
